# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.26.2/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.26.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dede/Code/Github/sipeto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dede/Code/Github/sipeto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.26.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.26.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dede/Code/Github/sipeto/CMakeFiles /home/dede/Code/Github/sipeto//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dede/Code/Github/sipeto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sipeto

# Build rule for target.
sipeto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sipeto
.PHONY : sipeto

# fast build rule for target.
sipeto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/build
.PHONY : sipeto/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/simple_http_server.o: src/simple_http_server.cpp.o
.PHONY : src/simple_http_server.o

# target to build an object file
src/simple_http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/simple_http_server.cpp.o
.PHONY : src/simple_http_server.cpp.o

src/simple_http_server.i: src/simple_http_server.cpp.i
.PHONY : src/simple_http_server.i

# target to preprocess a source file
src/simple_http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/simple_http_server.cpp.i
.PHONY : src/simple_http_server.cpp.i

src/simple_http_server.s: src/simple_http_server.cpp.s
.PHONY : src/simple_http_server.s

# target to generate assembly for a file
src/simple_http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/simple_http_server.cpp.s
.PHONY : src/simple_http_server.cpp.s

src/sipeto.o: src/sipeto.cpp.o
.PHONY : src/sipeto.o

# target to build an object file
src/sipeto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/sipeto.cpp.o
.PHONY : src/sipeto.cpp.o

src/sipeto.i: src/sipeto.cpp.i
.PHONY : src/sipeto.i

# target to preprocess a source file
src/sipeto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/sipeto.cpp.i
.PHONY : src/sipeto.cpp.i

src/sipeto.s: src/sipeto.cpp.s
.PHONY : src/sipeto.s

# target to generate assembly for a file
src/sipeto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sipeto.dir/build.make CMakeFiles/sipeto.dir/src/sipeto.cpp.s
.PHONY : src/sipeto.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sipeto"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/simple_http_server.o"
	@echo "... src/simple_http_server.i"
	@echo "... src/simple_http_server.s"
	@echo "... src/sipeto.o"
	@echo "... src/sipeto.i"
	@echo "... src/sipeto.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

